### ISSUE TITLE
Package install failed with errors

### ISSUE THREAD

**Issue by marcohoepner** [joe-jordan/pyvoro#23]
Hi,

i need some help to install the package.

My Python Version ist 3.11.3.
During the installation process i got always the following error messages:

Collecting pyvoro
  Downloading pyvoro-1.3.2.tar.gz (123 kB)
     ---------------------------------------- 123.5/123.5 kB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyvoro
  Building wheel for pyvoro (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      C:\Python311\Lib\site-packages\setuptools\dist.py:755: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      voroplusplus.cpp
      pyvoro/voroplusplus.cpp(678): error C2106: "=": Linker Operand muss ein L-Wert sein
      pyvoro/voroplusplus.cpp(699): error C2106: "=": Linker Operand muss ein L-Wert sein
      pyvoro/voroplusplus.cpp(1184): warning C4244: "=": Konvertierung von "Py_ssize_t" in "int", m”glicher Datenverlust
      pyvoro/voroplusplus.cpp(2571): error C2660: "PyCode_New": Funktion akzeptiert keine 15 Argumente
      C:\Python311\include\cpython/code.h(148): note: Siehe Deklaration von "PyCode_New"
      pyvoro/voroplusplus.cpp(2583): error C2660: "PyCode_New": Funktion akzeptiert keine 15 Argumente
      C:\Python311\include\cpython/code.h(148): note: Siehe Deklaration von "PyCode_New"
      pyvoro/voroplusplus.cpp(3063): warning C4996: 'PyUnicode_GET_SIZE': deprecated in 3.3
      pyvoro/voroplusplus.cpp(3079): warning C4996: 'PyUnicode_GET_SIZE': deprecated in 3.3
      pyvoro/voroplusplus.cpp(3995): error C2660: "PyCode_New": Funktion akzeptiert keine 15 Argumente
      C:\Python311\include\cpython/code.h(148): note: Siehe Deklaration von "PyCode_New"
      pyvoro/voroplusplus.cpp(4041): error C2027: Verwendung des undefinierten Typs "_frame"
      C:\Python311\include\pytypedefs.h(22): note: Siehe Deklaration von "_frame"
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyvoro
  Running setup.py clean for pyvoro
Failed to build pyvoro
ERROR: Could not build wheels for pyvoro, which is required to install pyproject.toml-based projects

Any help is welcome.

Best Regards
Marco

**Comment by LiyangPre** [comment]
Hello Macro, sorry to bother you. I've encountered the same question. May I ask have you fixed this problem？:)

**Comment by tu-maurice** [comment]
It seems this is a compatibility issue with python 3.11. It works with python 3.10 for me.

**Comment by LiyangPre** [comment]
> It seems this is a compatibility issue with python 3.11. It works with python 3.10 for me.

Thanks you! I've sovled this problem by downloading Visual Studio Build Tools. Maybe my issue comes from no suitable compiler?

**Comment by Nitroxyz** [comment]
> > It seems this is a compatibility issue with python 3.11. It works with python 3.10 for me.
> 
> Thanks you! I've sovled this problem by downloading Visual Studio Build Tools. Maybe my issue comes from no suitable compiler?

How did you solve it / What did you install? Issue is on windows, not linux

**Comment by VamosJxy** [comment]
I encounter the same problem. It stilll does not work although I have installed Visual Studio Build Tools... Is there anyone having a solution?

**Comment by Nitroxyz** [comment]
Use python version 3.10, any higher version breaks

**Comment by ClubSodaX** [comment]
> 我遇到了同样的问题。虽然我已经安装了 Visual Studio Build Tools，但它仍然不起作用...有人有解决方案吗？

Hello，now I meet the same problem , have you solved your problem?

**Comment by teosbpl** [comment]
I solved this problem. 
Steps:
python -m pip install -U cython
[upgrades cython to an actual version]
cd pyvoro
ls *.pyx (should be nonempty)
cythonize -i .\voroplusplus.pyx
After error that on line 161 double cannot be assigned to int I added type cast:
for j from 0 <= j < (int)(vertex_positions.size() / 3):
and ran cythonize again
[this operation regenerated the voroplusplus.cpp]
cd ..
python setup.py install
I have no time to provide a fix, most probably the cpp code should always be generated from pyx, which should work for all Python versions. But the steps to solve it are relatively easy.
Good luck
